//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCcrud1.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class registrationdetail
    {[Required]
     [StringLength(15,ErrorMessage ="Please enter a valid name")]
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        [Required]
        public int rollno { get; set; }
        [Required]
        public string student_address { get; set; }
       [Required]
        public string student_state { get; set; }
        [Required]
        [MinLength(11,ErrorMessage ="Please enter a valid mobile number")]
        public Nullable<int> mobile { get; set; }
    }
}
